### ISSUE TITLE
Consider whether throwing a JavaScriptException to the user is the right thing to do upon a save with a non-parsing file

### ISSUE THREAD

**Issue by koberidze** [semperos/screwdriver#3]
There may be merit instead in throwing a cleaner parse exception, rather than the full stack trace of the build monitor and interpreter chain.

**Comment by koberidze** [comment]
Pasting an example stack trace, since GitHub doesn't allow non-image issue attachments:

```
ERROR [Thread-2] (BuildListener.java:32) - An error occurred while monitoring the file system.
org.mozilla.javascript.JavaScriptException: Error: In timeline_container_view.coffee, Parse error on line 13: Unexpected 'IDENTIFIER' (coffee-script.js#11)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
    at script(coffee-script.js:11)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
    at org.mozilla.javascript.gen.CoffeeScriptCompiler_221._c_script_0(CoffeeScriptCompiler:1)
    at org.mozilla.javascript.gen.CoffeeScriptCompiler_221.call(CoffeeScriptCompiler)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
    at org.mozilla.javascript.gen.CoffeeScriptCompiler_221.call(CoffeeScriptCompiler)
    at org.mozilla.javascript.gen.CoffeeScriptCompiler_221.exec(CoffeeScriptCompiler)
    at org.mozilla.javascript.Context.evaluateReader(Context.java:1110)
    at com.semperos.screwdriver.js.rhino.RhinoCompiler.compile(RhinoCompiler.java:144)
    at com.semperos.screwdriver.js.rhino.RhinoCompiler.compile(RhinoCompiler.java:130)
    at com.semperos.screwdriver.js.CoffeeScriptCompiler.compile(CoffeeScriptCompiler.java:43)
    at com.semperos.screwdriver.js.CoffeeScriptCompiler.compile(CoffeeScriptCompiler.java:35)
    at com.semperos.screwdriver.build.BuildJs.compile(BuildJs.java:33)
    at com.semperos.screwdriver.build.BuildJs.processFile(BuildJs.java:44)
    at com.semperos.screwdriver.build.BuildAssetWithRhino.build(BuildAssetWithRhino.java:29)
    at com.semperos.screwdriver.watch.BuildListener.build(BuildListener.java:30)
    at com.semperos.screwdriver.watch.BuildListener.onFileChange(BuildListener.java:57)
    at org.apache.commons.io.monitor.FileAlterationObserver.doMatch(FileAlterationObserver.java:400)
    at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:334)
    at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:335)
    at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:335)
    at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:335)
    at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:335)
    at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304)
    at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by semperos** [comment]
In theory I'm not opposed to showing a more localized stack trace, but I would not limit it unless we provided a way to also get the full stack trace. Could be as simple as using different log levels, but I'd want that figured out first.

**Comment by koberidze** [comment]
I agree that the full track should be available somehow, my main point is that I prefer a user-facing exception to be flavored by the app throwing it.  In this case, for example, a ParseException that wraps and exposes the inner JavaScriptException.

**Comment by rheol** [comment]
## Adding another stack trace which I think could be made clearer (in particular, the "filename: null" is confusing) :

 INFO [com.semperos.screwdriver.scripting.clojure.MainClojure.main()](JsRuntimeSupport.java:30) - ERROR: LESS compilation error.
 INFO [com.semperos.screwdriver.scripting.clojure.MainClojure.main()](JsRuntimeSupport.java:30) - type     : Name
message     : .span3 is undefined
filename    : null
index       : 2998
line        : 97
callLine    : undefined
callExtract : undefined
stack       : undefined
column      : 2
extract     : .exercise-nav {,  .span3 !important;,}

ERROR [com.semperos.screwdriver.scripting.clojure.MainClojure.main()](RhinoEvaluatorException.java:17) - JavaScript Source Stacktrace
ERROR [com.semperos.screwdriver.scripting.clojure.MainClojure.main()](RhinoEvaluatorException.java:18) -   at LessCompiler:34
    at less.js:8
    at LessCompiler:4

org.mozilla.javascript.JavaScriptException: [object Object](LessCompiler#34)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
    at script(LessCompiler:34)
    at script(less.js:8)
    at script(LessCompiler:4)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
    at org.mozilla.javascript.Context.evaluateReader(Context.java:1110)
    at com.semperos.screwdriver.js.rhino.RhinoCompiler.compile(RhinoCompiler.java:144)
    at com.semperos.screwdriver.js.rhino.RhinoCompiler.compile(RhinoCompiler.java:130)
    at com.semperos.screwdriver.js.LessCompiler.compile(LessCompiler.java:38)
    at com.semperos.screwdriver.build.BuildCss.compile(BuildCss.java:29)
    at com.semperos.screwdriver.build.BuildCss.processFile(BuildCss.java:40)
    at com.semperos.screwdriver.build.BuildAssetWithRhino.build(BuildAssetWithRhino.java:29)
    at com.semperos.screwdriver.build.BuildAssetWithRhino.buildAll(BuildAssetWithRhino.java:35)
    at com.semperos.screwdriver.build.BuildAll.build(BuildAll.java:27)
    at screwdriver_build$run_build.invoke(screwdriver_build.clj:8)
    at screwdriver_build$run_build.invoke(screwdriver_build.clj:6)
    at screwdriver_build$eval64.invoke(screwdriver_build.clj:11)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5028.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4977.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at screwdriver_runner$eval37$loading__4920__auto____38.invoke(screwdriver_runner.clj:1)
    at screwdriver_runner$eval37.invoke(screwdriver_runner.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:357)
    at clojure.lang.RT.loadResourceScript(RT.java:349)
    at com.semperos.screwdriver.scripting.clojure.ClojureEval.evalResource(ClojureEval.java:26)
    at com.semperos.screwdriver.scripting.clojure.MainClojure.main(MainClojure.java:20)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:722)
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.mozilla.javascript.EvaluatorException: An unrecoverable JavaScript compilation error occurred. See above.
    at com.semperos.screwdriver.js.rhino.RhinoEvaluatorException.<init>(RhinoEvaluatorException.java:20)
    at com.semperos.screwdriver.js.rhino.RhinoEvaluatorException.<init>(RhinoEvaluatorException.java:24)
    at com.semperos.screwdriver.js.LessCompiler.compile(LessCompiler.java:40)
    at com.semperos.screwdriver.build.BuildCss.compile(BuildCss.java:29)
    at com.semperos.screwdriver.build.BuildCss.processFile(BuildCss.java:40)
    at com.semperos.screwdriver.build.BuildAssetWithRhino.build(BuildAssetWithRhino.java:29)
    at com.semperos.screwdriver.build.BuildAssetWithRhino.buildAll(BuildAssetWithRhino.java:35)
    at com.semperos.screwdriver.build.BuildAll.build(BuildAll.java:27)
    at screwdriver_build$run_build.invoke(screwdriver_build.clj:8)
    at screwdriver_build$run_build.invoke(screwdriver_build.clj:6)
    at screwdriver_build$eval64.invoke(screwdriver_build.clj:11)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5028.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4977.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at screwdriver_runner$eval37$loading__4920__auto____38.invoke(screwdriver_runner.clj:1)
    at screwdriver_runner$eval37.invoke(screwdriver_runner.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:357)
    at clojure.lang.RT.loadResourceScript(RT.java:349)
    at com.semperos.screwdriver.scripting.clojure.ClojureEval.evalResource(ClojureEval.java:26)
    at com.semperos.screwdriver.scripting.clojure.MainClojure.main(MainClojure.java:20)
    ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
